server:
  context-path: /hqeiServer
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hqei-server?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 123456
    max-active: 100
    driver-class-name: com.mysql.jdbc.Driver
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 18000000
    max-wait: 60000
    test-while-idle: true
    validation-query: select 1

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hqei.server.domain


