spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hqei-server?serverTimezone=UTC
    username: root
    password: 12345678

liquibase:
  change-log: classpath:config/liquibase/server/master.xml
  enabled: true
  drop-first: false
