spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hqei-data-process
    username: root
    password: 123456

liquibase:
  change-log: classpath:config/liquibase/data_process/master.xml
  enabled: true
  drop-first: false


