spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hqei-data-import-export?serverTimezone=UTC
    username: root
    password: 123456

liquibase:
  change-log: classpath:config/liquibase/import-export/master.xml
  enabled: true
  drop-first: false


